# this file is here to facilitate development/testing
# $ docker compose up -d --build --force-recreate
services:
  backup:
    build:
      context: .
      args:
        ALPINE_VERSION: '3.16'
    env_file:
      - .env
    environment:
      SCHEDULE: '@weekly'     # optional
      BACKUP_KEEP_DAYS: 28     # optional
      PASSPHRASE: $AWS_BACKUP_ENCRYPTION_KEY  # optional
      S3_REGION: $S3_REGION
      S3_ACCESS_KEY_ID: $AWS_BACKUP_ACCESS_KEY
      S3_SECRET_ACCESS_KEY: $AWS_BACKUP_SECRET_ACCESS_KEY
      S3_BUCKET: $AWS_S3_BACKUPS_BUCKET_NAME
      S3_PREFIX: backup
      POSTGRES_HOST: $POSTGRES_DB_HOST
      POSTGRES_DATABASE: $POSTGRES_DB_NAME
      POSTGRES_USER: $POSTGRES_DB_USER
      POSTGRES_PASSWORD: $POSTGRES_DB_PASSWORD
